# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./queries/initialization:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080